import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join, relative, resolve } from 'node:path'

const BASE = '/finance-tracker/'

// GitHub Pages 對所有檔案只回 cache-control: max-age=600，超過 10 分鐘後每次開啟
// 都得重新下載整包 JS/CSS，開啟速度因此受網路影響。這個外掛在 build 完成後產生
// dist/sw.js：安裝時把所有產物預快取，之後開啟一律先用快取（App Shell 秒開），
// 新版部署則由 Service Worker 更新機制在背景下載、於下次進入時套用。
function swPrecachePlugin() {
  return {
    name: 'sw-precache',
    apply: 'build',
    closeBundle() {
      const distDir = resolve(__dirname, 'dist')
      const files = []
      const walk = (dir) => {
        for (const name of readdirSync(dir)) {
          const p = join(dir, name)
          if (statSync(p).isDirectory()) walk(p)
          else files.push(p)
        }
      }
      walk(distDir)

      const hash = createHash('md5')
      const urls = []
      for (const f of files.sort()) {
        const rel = relative(distDir, f).split('\\').join('/')
        if (rel === 'sw.js') continue
        hash.update(rel)
        hash.update(readFileSync(f))
        // index.html 以目錄網址（BASE）為快取鍵，對應瀏覽器的 navigation request
        urls.push(rel === 'index.html' ? BASE : BASE + rel)
      }
      // 時間戳前綴（秒、定寬）讓快取名稱可依字典序排出新舊
      const version = `${Math.floor(Date.now() / 1000)}-${hash.digest('hex').slice(0, 10)}`

      const sw = `// generated by vite.config.js (sw-precache) — do not edit
const CACHE = 'ft-shell-${version}';
const BASE = '${BASE}';
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // cache: 'no-cache' — 安裝時繞過瀏覽器 HTTP 快取（GitHub Pages max-age=600），
      // 避免剛部署完的短暫視窗內把舊版 index.html 存進預快取
      .then((cache) => cache.addAll(PRECACHE.map((u) => new Request(u, { cache: 'no-cache' }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => {
        // 保留「最新的前一代」快取：新版 SW 接管瞬間，舊頁面可能仍在載入
        // 舊版資源（部署後伺服器上已不存在），需靠前一代快取撐過交接期
        const shells = keys.filter((k) => k.startsWith('ft-shell-') && k !== CACHE).sort();
        shells.pop(); // newest previous generation — keep it
        return Promise.all(shells.map((k) => caches.delete(k)));
      })
      .then(() => self.clients.claim())
  );
});

// 先查當前版本快取（確保拿到最新 shell），舊頁面交接期的舊資源
// 再退回跨快取查找（涵蓋保留的前一代），最後才走網路。
// 資產一律精確匹配 — 回應 URL 與請求 URL 不一致會被模組載入器拒收。
const fromCache = async (request, opts) => {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request, opts);
  if (hit) return hit;
  const legacy = await caches.match(request, opts);
  return legacy || fetch(request);
};

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Firestore / Finnhub 等跨網域請求一律直接走網路
  if (url.origin !== self.location.origin) return;

  if (req.mode === 'navigate') {
    // 導航用 BASE 當快取鍵（忽略 ?utm= 之類參數）
    event.respondWith(fromCache(BASE, { ignoreSearch: true }));
    return;
  }
  if (url.pathname.startsWith(BASE)) {
    event.respondWith(fromCache(req));
  }
});
`
      writeFileSync(join(distDir, 'sw.js'), sw)
      console.log(`[sw-precache] dist/sw.js generated (${urls.length} files, version ${version})`)
    }
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), swPrecachePlugin()],
  base: BASE,
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules/react-dom') || id.includes('node_modules/react/')) {
            return 'vendor-react';
          }
          if (id.includes('node_modules/firebase/')) {
            return 'vendor-firebase';
          }
          if (id.includes('node_modules/lucide-react/')) {
            return 'vendor-icons';
          }
        }
      }
    }
  }
})
